
import { $ } from "bun";
import { mkdir, rm, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { Glob } from "bun";

// Detect OS and Arch
const os = process.platform;
const arch = process.arch;

const validOS = ['linux', 'darwin', 'win32'];

if (!validOS.includes(os)) {
  console.error(`Unsupported OS: ${os}`);
  process.exit(1);
}

// Map node platform names to more common names
const osMap: Record<string, string> = {
  'linux': 'linux',
  'darwin': 'macos',
  'win32': 'windows'
};

const archMap: Record<string, string> = {
  'x64': 'x64',
  'arm64': 'arm64'
};

const targetOS = osMap[os];
const targetArch = archMap[arch] || arch;
const extension = os === 'win32' ? '.exe' : '';

const outputDir = "dist";
const cliOutputName = `tspm-${targetOS}-${targetArch}${extension}`;
const cliOutputPath = join(outputDir, cliOutputName);

console.log(`Building for ${targetOS} (${targetArch})...`);

// Ensure dist directory exists
await mkdir(outputDir, { recursive: true });

// Clean previous builds
try {
  await rm(join(outputDir, "index.js"), { force: true });
  await rm(join(outputDir, "index.cjs"), { force: true });
  await rm(join(outputDir, "cli"), { force: true, recursive: true });
  await rm(join(outputDir, "core"), { force: true, recursive: true });
  await rm(join(outputDir, "utils"), { force: true, recursive: true });
  await rm(join(outputDir, "public"), { force: true, recursive: true });
} catch {}

try {
  // ===== Step 1: Build Web Dashboard FIRST =====
  // This must happen before the CLI build so we can embed the built files
  console.log('\n📦 Building Web Dashboard...');
  const webOutDir = join(outputDir, 'public');
  await mkdir(webOutDir, { recursive: true });

  await $`bun build src/web/public/index.html --minify --asset-naming="[name].[ext]" --outdir ${webOutDir}`;
  console.log(`✅ Web Dashboard build successful: ${webOutDir}`);

  // ===== Step 2: Generate embed imports file =====
  // This file imports all built web assets so they get embedded into the standalone binary
  console.log('\n📦 Generating web asset embed file...');
  const webFiles = await readdir(webOutDir);
  const embedImports: string[] = [
    '// AUTO-GENERATED by build script - DO NOT EDIT',
    '// This file imports all web dashboard assets so they get embedded',
    '// into the standalone compiled binary via Bun\'s file embedding.',
    '',
  ];

  for (const file of webFiles) {
    // Use relative path from the embed file location to dist/public
    const relativePath = `../../dist/public/${file}`;
    embedImports.push(`import "./${file}" with { type: "file" };`);
  }

  embedImports.push('');

  // Write the embed file into dist/public so imports are co-located
  const embedFilePath = join(webOutDir, '_embed.ts');
  await writeFile(embedFilePath, embedImports.join('\n'));
  console.log(`✅ Embed file generated: ${embedFilePath}`);
  console.log(`   Embedding ${webFiles.length} web assets: ${webFiles.join(', ')}`);

  // ===== Step 3: Build standalone CLI executable with embedded web assets =====
  console.log('\n📦 Building standalone CLI executable (with embedded web assets)...');

  // Collect the built web files as additional entrypoints for embedding
  // const webAssetPaths = webFiles
  //   .filter(f => !f.startsWith('_')) // exclude our generated _embed.ts
  //   .map(f => join(webOutDir, f));

  // Use Bun.build() JS API to include both CLI entrypoint and web assets
  const result = await Bun.build({
    entrypoints: ['./src/cli/index.ts', embedFilePath],
    compile: {
      outfile: cliOutputPath,
    },
    minify: true,
    sourcemap: "linked",
    naming: {
      asset: "[name].[ext]",
    },
  });

  if (!result.success) {
    console.error('❌ CLI compile failed:');
    for (const log of result.logs) {
      console.error(`  ${log}`);
    }
    process.exit(1);
  }
  console.log(`✅ CLI build successful: ${cliOutputPath}`);

  // ===== Step 4: Build ESM module bundle =====
  console.log('\n📦 Building ESM module...');
  await $`bun build ./index.ts --outdir ${outputDir} --format esm --target bun`;
  console.log(`✅ ESM build successful: ${outputDir}/index.js`);

  // ===== Step 5: Build CJS module bundle =====
  console.log('\n📦 Building CJS module...');
  await $`bun build ./index.ts --outfile ${join(outputDir, 'index.cjs')} --format cjs --target bun`;
  console.log(`✅ CJS build successful: ${outputDir}/index.cjs`);

  // Copy package.json to dist
  console.log('\n📦 Copying package.json...');
  await $`cp package.json ${join(outputDir, 'package.json')}`;

  console.log(`\n🎉 Build completed successfully!`);
  console.log(`   - CLI: ${cliOutputPath} (with embedded web dashboard)`);
  console.log(`   - ESM: ${outputDir}/index.js`);
  console.log(`   - CJS: ${outputDir}/index.cjs`);
  console.log(`   - Web: ${webOutDir} (also embedded in CLI binary)`);
  
} catch (error) {
  console.error(`❌ Build failed:`, error);
  process.exit(1);
}
